version: '3.2'
services:
  api:
    container_name: "pemilu"
    image: "pemilu"
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4890:4890"